#!/usr/bin/env python3
"""
YOLO 학습 데이터 자동 수집 스크립트

현재 펜 감지기로 자동 라벨링하여 YOLO 학습 데이터를 수집합니다.
손으로 가린 이미지는 나중에 수동 보정이 필요합니다.

Usage:
    python collect_yolo_data.py                    # 기본 수집
    python collect_yolo_data.py --output ./data    # 출력 폴더 지정
    python collect_yolo_data.py --interval 0.5     # 0.5초마다 저장

Output structure:
    output/
    ├── images/
    │   ├── train/
    │   └── val/
    └── labels/
        ├── train/
        └── val/

YOLO format: class_id x_center y_center width height (normalized 0~1)
"""

import os
import sys
import cv2
import numpy as np
import time
import argparse
from datetime import datetime
from pathlib import Path

# 같은 디렉토리의 모듈 import
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from pen_detector_advanced import AdvancedPenDetector, DetectionState


class YOLODataCollector:
    """YOLO 학습 데이터 수집기"""

    def __init__(self, output_dir: str = "./yolo_dataset", val_ratio: float = 0.2):
        """
        Args:
            output_dir: 출력 디렉토리
            val_ratio: 검증 데이터 비율 (0.2 = 20%)
        """
        self.output_dir = Path(output_dir)
        self.val_ratio = val_ratio

        # 디렉토리 생성
        self.train_images = self.output_dir / "images" / "train"
        self.train_labels = self.output_dir / "labels" / "train"
        self.val_images = self.output_dir / "images" / "val"
        self.val_labels = self.output_dir / "labels" / "val"

        for d in [self.train_images, self.train_labels, self.val_images, self.val_labels]:
            d.mkdir(parents=True, exist_ok=True)

        # 클래스 정의
        self.classes = ["pen"]

        # 통계
        self.total_saved = 0
        self.train_count = 0
        self.val_count = 0

        # data.yaml 생성
        self._create_data_yaml()

    def _create_data_yaml(self):
        """YOLO 학습용 data.yaml 생성"""
        yaml_content = f"""# YOLO Pen Detection Dataset
# Auto-generated by collect_yolo_data.py

path: {self.output_dir.absolute()}
train: images/train
val: images/val

nc: {len(self.classes)}
names: {self.classes}
"""
        yaml_path = self.output_dir / "data.yaml"
        with open(yaml_path, 'w') as f:
            f.write(yaml_content)
        print(f"[Collector] Created {yaml_path}")

    def save_sample(self, image: np.ndarray, bbox: tuple,
                    confidence: float, force_val: bool = False) -> bool:
        """
        샘플 저장

        Args:
            image: BGR 이미지
            bbox: (x, y, w, h) 픽셀 좌표
            confidence: 감지 신뢰도
            force_val: True면 무조건 val에 저장

        Returns:
            성공 여부
        """
        if bbox is None or confidence < 0.5:
            return False

        x, y, w, h = bbox
        img_h, img_w = image.shape[:2]

        # YOLO 포맷으로 변환 (normalized)
        x_center = (x + w / 2) / img_w
        y_center = (y + h / 2) / img_h
        w_norm = w / img_w
        h_norm = h / img_h

        # 범위 체크
        if not (0 <= x_center <= 1 and 0 <= y_center <= 1):
            return False
        if not (0 < w_norm <= 1 and 0 < h_norm <= 1):
            return False

        # train/val 결정
        is_val = force_val or (np.random.random() < self.val_ratio)

        if is_val:
            img_dir = self.val_images
            label_dir = self.val_labels
            self.val_count += 1
        else:
            img_dir = self.train_images
            label_dir = self.train_labels
            self.train_count += 1

        # 파일명 생성
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S_%f")
        filename = f"pen_{timestamp}"

        # 이미지 저장
        img_path = img_dir / f"{filename}.jpg"
        cv2.imwrite(str(img_path), image)

        # 라벨 저장 (class_id x_center y_center width height)
        label_path = label_dir / f"{filename}.txt"
        with open(label_path, 'w') as f:
            f.write(f"0 {x_center:.6f} {y_center:.6f} {w_norm:.6f} {h_norm:.6f}\n")

        self.total_saved += 1
        return True

    def get_stats(self) -> dict:
        """통계 반환"""
        return {
            "total": self.total_saved,
            "train": self.train_count,
            "val": self.val_count
        }


def main():
    parser = argparse.ArgumentParser(description="YOLO 펜 데이터 수집")
    parser.add_argument("--output", type=str, default="./yolo_dataset",
                       help="출력 디렉토리")
    parser.add_argument("--interval", type=float, default=0.3,
                       help="저장 간격 (초)")
    parser.add_argument("--max-samples", type=int, default=500,
                       help="최대 샘플 수")
    parser.add_argument("--val-ratio", type=float, default=0.2,
                       help="검증 데이터 비율")
    args = parser.parse_args()

    print("=" * 60)
    print("YOLO 펜 데이터 수집기")
    print("=" * 60)
    print(f"출력 폴더: {args.output}")
    print(f"저장 간격: {args.interval}초")
    print(f"최대 샘플: {args.max_samples}")
    print("=" * 60)
    print("조작법:")
    print("  Space: 수동 저장")
    print("  a: 자동 저장 토글")
    print("  v: 다음 샘플은 val에 저장")
    print("  q: 종료")
    print("=" * 60)

    # 감지기 초기화
    detector = AdvancedPenDetector()
    if not detector.start():
        print("카메라 시작 실패!")
        return

    # 수집기 초기화
    collector = YOLODataCollector(args.output, args.val_ratio)

    auto_save = False
    force_val = False
    last_save_time = 0

    try:
        while collector.total_saved < args.max_samples:
            # 감지
            result = detector.detect()
            color_image, _ = detector.get_frames()

            if color_image is None:
                continue

            display = color_image.copy()

            # 감지 결과 시각화
            if result and result.state == DetectionState.DETECTED:
                if result.bbox:
                    x, y, w, h = result.bbox
                    cv2.rectangle(display, (x, y), (x+w, y+h), (0, 255, 0), 2)

                    # 자동 저장
                    current_time = time.time()
                    if auto_save and (current_time - last_save_time) >= args.interval:
                        if collector.save_sample(color_image, result.bbox,
                                                 result.confidence, force_val):
                            last_save_time = current_time
                            force_val = False

            # 상태 표시
            stats = collector.get_stats()
            status_lines = [
                f"Total: {stats['total']}/{args.max_samples}",
                f"Train: {stats['train']}, Val: {stats['val']}",
                f"Auto: {'ON' if auto_save else 'OFF'}",
                f"Next->Val: {'YES' if force_val else 'NO'}"
            ]

            for i, line in enumerate(status_lines):
                color = (0, 255, 0) if auto_save else (255, 255, 255)
                cv2.putText(display, line, (10, 30 + i * 25),
                           cv2.FONT_HERSHEY_SIMPLEX, 0.6, color, 2)

            cv2.imshow("YOLO Data Collector", display)

            key = cv2.waitKey(30) & 0xFF

            if key == ord('q'):
                break
            elif key == ord(' '):  # 수동 저장
                if result and result.bbox:
                    if collector.save_sample(color_image, result.bbox,
                                             result.confidence, force_val):
                        print(f"저장됨! (Total: {stats['total'] + 1})")
                        force_val = False
            elif key == ord('a'):  # 자동 저장 토글
                auto_save = not auto_save
                print(f"자동 저장: {'ON' if auto_save else 'OFF'}")
            elif key == ord('v'):  # 다음은 val에 저장
                force_val = True
                print("다음 샘플 -> Val")

    except KeyboardInterrupt:
        pass

    # 정리
    detector.stop()
    cv2.destroyAllWindows()

    # 결과 출력
    stats = collector.get_stats()
    print("\n" + "=" * 60)
    print("수집 완료!")
    print("=" * 60)
    print(f"총 샘플: {stats['total']}")
    print(f"  - Train: {stats['train']}")
    print(f"  - Val: {stats['val']}")
    print(f"\n데이터 위치: {args.output}")
    print("\nYOLO 학습 명령어:")
    print(f"  yolo detect train data={args.output}/data.yaml model=yolov8n.pt epochs=100")
    print("=" * 60)


if __name__ == "__main__":
    main()
